# Generated by Django 5.0.1 on 2025-07-10 14:57

import propylon_document_manager.file_versions.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", propylon_document_manager.file_versions.models.UserManager()),
            ],
        ),
    ]
