# Generated by Django 5.0.1 on 2025-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
