# Generated by Django 5.0.1 on 2025-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0005_remove_fileversion_file_name_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="content_hash",
            field=models.CharField(db_index=True, default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
